name: ShellCheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ShellCheck
      run: sudo apt install -y shellcheck
    - name: ShellCheck install.sh
      run: shellcheck install.sh
